-- This module is the root of the GreenGriffithsLangConjectureCanonicalLaneLean Lean proof package.
import GreenGriffithsLangConjectureCanonicalLaneLean.Basic
import GreenGriffithsLangConjectureCanonicalLaneLean.SourcePackage
import GreenGriffithsLangConjectureCanonicalLaneLean.SourceDependencies
import GreenGriffithsLangConjectureCanonicalLaneLean.Formalization
import GreenGriffithsLangConjectureCanonicalLaneLean.ReviewerBridge
import GreenGriffithsLangConjectureCanonicalLaneLean.TheoremStatement
import GreenGriffithsLangConjectureCanonicalLaneLean.MathlibStatement
