-- This module is the root of the GreenGriffithsLangConjectureCanonicalLaneLean Lean proof package.
import GreenGriffithsLangConjectureCanonicalLaneLean.Basic
import GreenGriffithsLangConjectureCanonicalLaneLean.SourcePackage
import GreenGriffithsLangConjectureCanonicalLaneLean.SourceDependencies
import GreenGriffithsLangConjectureCanonicalLaneLean.Formalization
import GreenGriffithsLangConjectureCanonicalLaneLean.ReviewerBridge
import GreenGriffithsLangConjectureCanonicalLaneLean.TheoremStatement
import GreenGriffithsLangConjectureCanonicalLaneLean.MathlibObjects
import GreenGriffithsLangConjectureCanonicalLaneLean.AdmissibleClass
import GreenGriffithsLangConjectureCanonicalLaneLean.Projection
import GreenGriffithsLangConjectureCanonicalLaneLean.BridgeLemmas
import GreenGriffithsLangConjectureCanonicalLaneLean.GateLemmas
import GreenGriffithsLangConjectureCanonicalLaneLean.FinalTheorem
import GreenGriffithsLangConjectureCanonicalLaneLean.MathlibStatement
